### PR TITLE
Add multiple outputs

### LINKED ISSUE #7: I unintentionally created a duplicate at slack_sdk-feedstock
Unfortunately I somehow missed this feedstock and created this one:

https://github.com/conda-forge/slack_sdk-feedstock/

Do you know the proper procedure for cleaning this up? Can we add `slack_sdk` as an output here and delete my feedstock?

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Closes #7

### CODE REVIEW

**Comment by maresb** [comment]
I'm not so sure what to put in the top-level `build:` block vs the outputs.

For some reason the Jinja2 variable {{ PYTHON }} doesn't work. And the build process in general seems to be very flaky.

**Comment by xylar** [comment]
@maresb, I'm traveling this weekend but will take a look and make some suggestions as soon as I can. I'll find a split, noarch feedstock as an example as soon as I can.

**Comment by maresb** [comment]
And now even after you merged, GitHub is showing the diff from HEAD as of when I opened the PR. :laughing:

Maybe if I close and reopen?

**Comment by maresb** [comment]
Ah, ok, thanks @xylar. I suppose there's little time pressure until the next release comes out. I'll play around a little bit more and see if I can figure it out.

**Comment by maresb** [comment]
@xylar I'm pretty sure I got it. 

I'll let you hit the merge button.

**Comment by xylar** [comment]
@maresb, this looks great! I think we should maybe rename the main package "slack-sdk-split"? This seems to be what most split packages like this do. Maybe there are issues when the main package and one of the outputs have the same name.

**Comment by xylar** [comment]
Looking at the conda-build docs, I don't see any reason it should be a problem to have the main package and one of the subpackages have the same name. Nothing should get built for the main package.

**Comment by xylar** [comment]
@maresb thanks for working on this! I wasn't sure how much experience you have with conda but clearly plenty!

**Pull request merged**
